name: my_shop
description: Sample ecommerce with clean architecture and tdd.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: 2.5.2

dependencies:
  dartz: ^0.10.0
  data_connection_checker: ^0.3.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  get_it: ^7.2.0
  http: ^0.13.4
  shared_preferences: ^2.0.8

dev_dependencies:
  bloc_test: ^8.3.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16

flutter:
  uses-material-design: true
